### ISSUE TITLE
[Front] 헤더 만들기

### ISSUE THREAD

**Issue by ramrami-B** [BaekGuu/baekgu-front#1]
## 🌲Description
피그마 디자인
![피그마 디자인](https://github.com/BaekGuu/baekgu-front/assets/74824057/6df748bf-cdc9-4cba-86d6-54e5a52939c2)

## ✔Todo
- [x] 로고 부분 만들기
- [x] 로고를 누르면 메인페이지('/')로 이동
- [x] 쿠키에 사용자 정보가 없을 땐 "로그인" "회원가입"이 뜨고, 로그인 이후에는 환영멘트 띄우기
- [x] 환영멘트 부분 누르면 회원 정보 수정과 로그아웃 버튼
- [x] 로그아웃 누르면 쿠키 삭제(=로그아웃)
- [ ] 회원 정보 수정을 누르면 회원 수정 페이지('/mypage')로 이동
- [x] 각 메뉴를 누르면 라우팅 되고 현재 페이지에 해당하는 메뉴에 active 효과 주기
